# -*- coding: utf-8 -*-
"""Population Camp Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phmM7uJx5vTNpAues1AQEL1sJwO2t-_L
"""

import pandas as pd

df = pd.read_excel("/content/4_6007878812891618215.xlsx")

df.head()

Population_Clean = df.copy()

Population_Clean.head()

Population_Clean["Date"] = pd.to_datetime(
    Population_Clean["Date"],
    errors="coerce"
)

text_columns = ["Country", "City", "PlaceName"]

for col in text_columns:
    Population_Clean[col] = Population_Clean[col].astype("string")

number_columns = [
    "Members", "Male", "Female",
    "Room", "Flat", "House", "Tent"
]

for col in number_columns:
    Population_Clean[col] = pd.to_numeric(
        Population_Clean[col],
        errors="coerce"
    ).astype("Int64")

text_columns = ["Country", "City", "PlaceName"]

for col in text_columns:
    Population_Clean[col] = (
        Population_Clean[col]
        .str.strip()
        .str.capitalize()
    )

# 10. Handle structural missing values by replacing nulls with 0
housing_cols = ['Room', 'Flat', 'House', 'Tent']
df[housing_cols] = df[housing_cols].fillna(0)

Population_Clean[housing_cols].isna().sum()

Population_Clean = Population_Clean.dropna(how='all')
Population_Clean = Population_Clean.drop_duplicates()

Population_Clean.duplicated().sum()

import numpy as np

df['Member_Validation'] = np.where(df['Members'] == (df['Male'] + df['Female']), 'OK', 'Review')
print(df['Member_Validation'].head())

# Ensure Date column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Create Year and Month fields
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()

df.to_excel('cleaned_data.xlsx', index=False)
